[project]
name = "gcacw-scenario-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pdfplumber>=0.11.9",
    "pillow>=12.1.0",
    "pytest>=8.0.0",
]
