[project]
name = "gcacw-scenario-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "pdfplumber>=0.11.9",
]
